### ISSUE TITLE
Where are My Files

### ISSUE THREAD

**Issue by astorm** [magento/magento2devbox-web#20] opened 2017-01-19 20:11 UTC
I have a running dev box instance.  I can load a Magento system at 

http://127.0.0.1:32769/

Where are my files?  I'm a PHP developer who wants to use this dev box to dev.  Deving as a PHP developer means creating and editing files.  Where are my files?

Expected Behavior: I can add files to my system to dev

Actual Behavior: There are no files to be seen anywhere and no explanation of where they are

**Comment by piotrekkaminski** [comment] 2017-01-19 20:18
the files are in ./shared/webroot folder @astorm .

@xcomSteveJohnson make sense to add this to docs.

**Comment by fooman** [comment] 2017-01-19 20:30
As you can configure this in the DevBox wizard it could make sense to display this the same as the URLs.

**Comment by xcomSteveJohnson** [comment] 2017-01-19 23:08
@astorm Added [a section in the reference topic](http://devdocs.magento.com/guides/v2.1/install-gde/docker/docker-ref.html#devbox-fileshare) (How Magento uses file sharing) to cover this.

Contact us or open a PR on devdocs if it's not clear or if it's incorrect.

**Comment by vrann** [comment] 2017-01-20 22:25
@astorm Does it makes sense? 
Closing it now, please reopen if the issue is not resolved for you.

**Closed by vrann** 2017-01-20 22:25 UTC
Labels: question
